### ISSUE TITLE
Data Standard for Grant Making 

### ISSUE THREAD

**Issue by morchickit** [alphagov/tech-and-data-standards#63] opened 2018-08-15 10:22 UTC
## Category
- [X ] Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> Mor Rubinstein, 360Giving Data Labs Manager 

## Short Description
> According to the [NCVO Almanac](https://data.ncvo.org.uk/a/almanac18/income-from-government-2015-16/), the UK Government has been providing 32% of the income to the voluntary sector, in forms of grants and contracts.  The UK government has adopted the Open Contracting standard ([OCDS version 1.1](https://www.gov.uk/government/publications/open-standards-for-government/open-contracting-data-standard-profile)), but still didn't adopt any standard for grant making. However, the UK government has already committed to publish all of its grants data as part of the Open Government Partnership National Action Plan. 

The 360Giving standard was created to deal with the needs of grantmakers in the UK and is customised to help them share data together to make decisions, and can help government to share its grants data. 
 
## User Need
- As a grantmaker, I want to know who else if giving to a specific theme, so I can collaborate with them. 
- As a civil society organisation, I want to know who gives grants in my area, so I can apply to them. 
- As a local authority I want to see who get the grants, so I can assess the health of civil society in my area. 
 
## Expected Benefits
- Support in implementing the  [government civil society strategy]|(https://www.gov.uk/government/publications/civil-society-strategy-building-a-future-that-works-for-everyone) 
- Ability to compare between the contracting and grants since both Open Contracting and 360Giving are interoperable. 
- A better understanding of both government, lottery and trust and foundations investment in civil society, which will allow better funding decisions. 
 
## Functional Needs
A machine readable file in CSV or JSON complying with the 360Giving schema. See full details of the current [360Giving schema](http://standard.threesixtygiving.org/en/latest/reference/#spreadsheet-format) for functional needs.

**Comment by edent** [comment] 2018-08-15 15:36
Thank you for this great suggestion!  A couple of questions before we proceed.

I see that the Mayor of London has committed to publishing in this format - https://www.london.gov.uk/city-hall-blog/city-hall-publish-funding-data-360giving - do you know if they conducted a formal assessment of it?

Do you know of any UK government departments which are already publishing using this standard?

Thanks 👍

**Comment by morchickit** [comment] 2018-08-15 15:51
The GLA actually have already published their data earlier this month, you can see it here: https://data.london.gov.uk/download/gla-grants-data/b8108df0-cbbd-41e5-9567-345fa5f1385f/GLA%20grants%202014-17.xlsx 

I can find out about the formal assessment of it, 

Cabinet office has published data for Department of Transport and Ministry of Justice. This can be found here: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/663589/GGIS_Grant_Awards_2016_to_2017_2017-10-27_1621.xlsx

You can see all the details about 360Giving publishers on the registry - http://data.threesixtygiving.org/

**Comment by timgdavies** [comment] 2018-08-20 11:57
There is also an [Open Government Partnership Commitment](https://www.gov.uk/government/publications/uk-open-government-national-action-plan-2016-18/uk-open-government-national-action-plan-2016-18#commitment-6-grants-data) to publish data in line with the 360 Giving data standard.

**Comment by edent** [comment] 2018-08-20 18:11
Excellent! We have a strong use-case, departments already using it, and high-level endorsement.

@Lawrence-G will start work on the formal assessment. I expect that to be concluded by next week, but we will probably have some questions for the 360Giving team, so it might depend on how quickly they can answer.

In the meantime, if anyone else has comments, please let us know.

**Comment by Lawrence-G** [comment] 2018-08-24 14:34
## 360Giving Data Standard Assessement 

http://standard.threesixtygiving.org/en/latest/reference/#spreadsheet-format

### Formal specification

**Q. 1.** *Does it address and aid interoperability between public administrations?*


**A. Yes**
Allowing the grant-giving departments in government and other organisations to publish, use and reuse grant data in a standardised way. It will allow grantmaking to be tracked between the local and national level.

**Q. 2.** *Does it address and aid the development of digital services in government?*


**A. Yes**
By making it easier to publish and consume the data.

**Q. 3.** *Are the functional and non-functional requirements for the use and implementation of the specification clearly defined?*


**A. Yes**
The requirements are explained in this document http://standard.threesixtygiving.org/en/latest/reference/#data-formats




**Q. 4.** *Is it possible to implement the specification across different domains?*


**A.Yes**
The standard defines two formats (tabular data and JSON) which can be used by different departments or organisations publishing grant data. 


**Q. 5.** *Is it largely independent from products of single providers, either open source or proprietary?*


**A. Yes**
The data can be published using products from any provider that supports spreadsheets or JSON format data 

**Q. 6.** *Is it largely independent from specific platforms?*


**A.Yes**
The standard is not limited to a specific platform. This is helped by its support both for spreadsheets and the JSON format.

**Q. 7.** *Has the standard been written so that it can be delivered or used with more than one technology (for example XML and JSON)?*


**A. Yes**
JSON and tabular data format (spreadsheet)

**Q. 8.** *Has the specification been sufficiently developed and existed long enough to overcome most of its initial problems?*


**A.Yes**
Though a fairly new standard it has been iteratively developed (starting in 2014) and has been used to successfully publish data for the last three years.

**Q. 9.** *Are there existing or planned mechanisms to assess its conformity and implementation - for example conformity tests, certifications and plugfests?*


**A. Yes**
The data quality tool to assess conformity before publication of data
https://dataquality.threesixtygiving.org/




**Q. 10.** *Does it have sufficient detail, consistency and completeness for the use and development of products?*


**A.Yes**
Products in this case would most likely be web apps that can be developed to give access to grant data[a].





## Implementation of the formal specification




**Q. 11.** *Does it provide current implementation guidelines and documentation for the implementation of products?*


**A.Yes**
Notes for developers are contained in the documentation



**Q. 12.** *Does it provide a reference (or open source) implementation?*


**A.Yes**
Templates are provided for Spreadsheets,CSV and JSON Schemas
http://standard.threesixtygiving.org/en/latest/
Examples of datasets made to the standards are published here
http://data.threesixtygiving.org/





**Q. 13.** *Does it address backwards compatibility with previous versions?*


**A. Yes**
The versioning and revision control states “That backwards compatibility will be maintained wherever possible.”

**Q. 14.** *Are the underlying technologies for implementing it proven, stable and clearly defined?*


**A.Yes**
A text based standard. CSV and JSON implementation

## Openness


**Q. 15.** *Is information on the terms and policies for the establishment and operation of the standardisation organisation publicly available?*


**A.Yes**
See governance statement here
http://standard.threesixtygiving.org/en/latest/governance/#stewardship-and-governance




**Q. 16.** *Is participation in the creation process of the formal specification open to all relevant stakeholders (such as organisations, companies or individuals)?*


**A.Yes**
Via GitHub, “changes to the Standard can be proposed by anyone at any point via the 360Giving discussion forum either as issues for discussion, or pull requests” There are also standard Stewardship Committee meetings where the specification can be developed.

**Q. 17.** *Is information on the standardisation process publicly available?*


**A.Yes**
Published here
http://standard.threesixtygiving.org/en/latest/governance/#proposals





**Q. 18.** *Is information on the decision-making process for approving formal specifications is publicly available?*


**A.Yes**
See here http://standard.threesixtygiving.org/en/latest/governance/#review-by-the-stewardship-committee



**Q. 19.** *Are the formal specifications approved in a decision-making process which aims at reaching consensus?*


**A.Yes**
As stated in the standard document “Consensus: The process should act in the interest of the data standard, with particular consideration given to what the changes will mean for current publishers. All processes should aim towards gaining community consensus for changes.”

**Q. 20.** *Are the formal specifications reviewed using a formal review process with all relevant external stakeholders (such as public consultation)?*


**A.Yes**
The review process is described here -http://standard.threesixtygiving.org/en/latest/governance/#review-by-the-stewardship-committee



**Q. 21.** *Can all relevant stakeholders formally appeal or raise objections to the development and approval of formal specifications?*


**A.Yes**
During the review process

**Q. 22.** *Is relevant documentation of the development and approval process of formal specifications publicly available (such as preliminary results and committee meeting notes)?*


**A.Yes**
Development documentation is published here
http://standard.threesixtygiving.org/en/latest/governance/# 
Review panel meeting notes published here -
https://forum.threesixtygiving.org/t/standard-stewardship-committee-minutes/161





## Access to the formal specification


**Q. 23.** *Is the documentation publicly available for implementation and use at zero or low cost?*


**A.Yes**
http://standard.threesixtygiving.org/en/latest/



**Q. 24.** *Is the documentation of the intellectual property rights publicly available (is there a clear and complete set of licence terms)?*


**A.Yes**
The documentation has a clear statement.
http://standard.threesixtygiving.org/en/latest/governance/#intellectual-property
The schema is provided under a Creative Commons Attribution 4.0 International License.
Contributors to the Standard agree to transfer any copyright in their contributions to 360Giving, in order that it is held in trust as part of the Standard. No content infringing upon third-party Intellectual Property Rights will be included in the Standard.



**Q. 25.** *Is it licensed on a royalty-free basis?*


**A. Yes**
Under a Creative Commons Attribution 4.0 International License

## Versatility/flexibility of the proposed standard


**Q. 26.** *Has the formal specification been used for different implementations by different vendors/suppliers?*


**A.Yes**
Over 80 organisations have published data using this standard
http://data.threesixtygiving.org/



**Q. 27.** *Has the formal specification been used in different industries, business sectors or functions?*


**A.Yes**
By government departments, charitable organisations and private foundations.


**Q. 28.** *Has interoperability been demonstrated across different implementations by different vendors/suppliers?*


**A.Yes**
Interoperability is enabled by the standard. The data shared can be easily reused.
The data held in registries can be used to inform grantmakers and receivers.

## End user effect of the formal specification


**Q. 29.** *Do the products that implement it have a significant market share of adoption?*


**A.Not Applicable**
The standards for publishing data rather than building products. 

**Q. 30.** *Do the products that implement it target a broad spectrum of end-uses?*


**A.Not Applicable**



**Q. 31.** *Does it have strong support from different interest groups?*


**A.Yes**
Strong support from contributors on the GitHub repository and from organisations that want to publish data in the standard.

**Q. 32.** *Is there evidence that the adoption of it supports improving efficiency and effectiveness of organisational process?*


**A.Yes**
It is expected to, as described in the UK Open Government National Action Plan to release grants data in machine readable format: https://www.gov.uk/government/publications/uk-open-government-national-action-plan-2016-18/uk-open-government-national-action-plan-2016-18#commitment-6-grants-data



**Q. 33.** *Is there evidence that the adoption of it makes it easier to migrate between different solutions from different providers?*


**A. Not Applicable**



**Q. 34.** *Is there evidence that the adoption of it positively impacts the environment?*


**A.Yes**
It is possible the data that is now being published in the registers was published in paper reports.

**Q. 35.** *Is there evidence that the adoption of it positively impacts financial costs?*


**A.Yes**
The data helps to better understand spending and increase collaboration in matching resources to need. 



**Q. 36.** *Is there evidence that the adoption of it positively impacts security?*


**A.Not Applicable**
The standard does not impact security.


**Q. 37.** *Is there evidence that the adoption of it can be implemented alongside enterprise security technologies?*


**A.Not Applicable**



**Q. 38.** *Is there evidence that the adoption of it positively impacts privacy?*


**A.Not Applicable**



**Q. 39.** *Is it largely compatible with related (not alternative) formal specifications in the same area of application?*


**A.Yes**
The tabular data and JSON formats should be compatible with data in related formats.

**Q. 40.** *Is there evidence that the adoption of it positively impacts accessibility and inclusion?*


**A.Yes**
The standard allows data to be presented in accessible formats.

## Maintenance of the formal specification


**Q. 41.** *Does it have a defined maintenance organisation?*


**A.Yes**
360Giving data support team and the Stewardship Committee.


**Q. 42.** *Does the maintenance organisation provide sufficient finance and resource to control short-to-medium-term threats?*


**A.Yes**
Funding information here http://www.threesixtygiving.org/about/governance/



**Q. 43.** *Does the maintenance organisation have a public statement on intention to transfer responsibility for maintenance of it, if the organisation were no longer able to continue?*


**A. No**
 

**Q. 44.** *Does it have a defined maintenance and support process?**


**A.Yes**
The standard’s support processes are published here: http://standard.threesixtygiving.org/en/latest/governance/#support-policy




**Q. 45.** *Does it have a defined policy for version management?*


**A.Yes**
See the versioning section in the governance document:
http://standard.threesixtygiving.org/en/latest/governance/#versioning-and-upgrade-process

### Related European standards


**Q. 46.** *Is this an existing European standard or an identified technical specification in Europe? (Note: CEN, CENELEC or ETSI are the European standards bodies. Technical specifications provided by organisations other than CEN, CENELEC or ETSI can be under consideration to become a European standard or an identified technical specification in Europe.)*


**A.No**

**Q. 47.** *Does this specification or standard cover an area different from those already identified or currently under consideration as an identified European standard or specification?*


**A.Yes**

**Comment by Lawrence-G** [comment] 2018-09-06 13:09
For information -
The Government grants register has just been updated. CSV in 360G schema (apparently) ready for download or view online.
https://www.gov.uk/government/publications/government-grants-register

There are errors, though, when I run it through the validator.
I'm ignoring the Excel format download for now.

**Comment by stevieflow** [comment] 2018-09-08 08:52
@Lawrence-G thanks

The only file using the 360Giving standard on https://www.gov.uk/government/publications/government-grants-register is the award-level data:

![grants](https://user-images.githubusercontent.com/1209944/45252338-8d0b1400-b34c-11e8-8189-c85001881722.png)

This was briefly invalid with the 360Giving schema, but has been fixed.  This file is listed on the 360Giving Registry, also: http://data.threesixtygiving.org/ (which includes a nightly check against the schema):

![registry](https://user-images.githubusercontent.com/1209944/45252359-c9d70b00-b34c-11e8-9d20-92e56b260fbe.png)

**Comment by RKHayden** [comment] 2018-09-18 15:45
One of the difficulties in developing the Government Grants Information System mentioned in https://www.gov.uk/government/publications/government-grants-register is that what a grant is can be many different things. The government allocates funds to some arms-length bodies through grants. Some of those arms-length bodies then use those funds to award grants to others. They're very different things. And a grant given to the voluntary sector may be something very different again. Producing a schema relevant to all of those would be a challenge. Looking at the 360Giving Schema, it wouldn't work, for example, for grants awarded for research and innovation.

**Comment by Lawrence-G** [comment] 2018-09-24 13:55
@RKHayen, thank you for your comments. Can you expand on this a little? You highlighted the problem of a ‘chain’ of grant giving which may cause a problem. Is a problem with the schema used or the framework in which it is applied?
How would the schema not work for research and innovation? There are a number of such grants in the government grant register.

**Comment by timgdavies** [comment] 2018-09-28 11:35
Although it's not included in the default 360 Giving spreadsheet template (which just picks out the fields most relevant to charitable grant givers), it is possible to include detailed classifications of the funding type and grant purpose using 360 Giving. This may be helpful for cases like innovation grants, where there is a need to specify some additional information about the kind of grant. 

If you check the schema browser at http://standard.threesixtygiving.org/en/latest/reference/#giving-json-schemas you will see `fundingType` and `classification` objects, which consist of a classification scheme, code and value.

The design of this is to allow detailed classification of grants against different codelists. For example, in the below (very quickly) made up example, I've imagined there is a grant which has a **funding type** based on a codelist from the publisher (therefore they use their 360G-EX prefix to namespace the codelist), and then which is also classified against an established sectoral classification (COFOG) for the focus of the innovation funded. 

| Identifier | Title            | Description          | Currency | Amount Awarded | Award Date | Funding Type:Vocabulary | Funding Type:Code | Funding Type:Title | Funding Type:Description    | Classifications:Vocabulary | Classifications:Code | Classifications:Title | Classifications:Description    | Related Activity | Last modified | Data Source | 
|------------|------------------|----------------------|----------|----------------|------------|-------------------------|-------------------|--------------------|-----------------------------|----------------------------|----------------------|-----------------------|--------------------------------|------------------|---------------|-------------| 
| 360G-EX    | Innovation grant | Grant for innovation | GBP      | 5000           | 26/09/18   | 360G-EX                 | INNOVATION        | Innovation         | Funding for innovation work | COFOG                      | 05.1                 | Waste management      | Innovation in waste management |                  |               |             | 

Note that there is also the `relatedActivity` field which can be used to articulate the connection between a grant, and some parent grant. 

*Technical note*

Alternative templates from the 360 Giving spec can be constructed either by (a) manually adding new columns, [using the titles given here](http://standard.threesixtygiving.org/en/latest/reference/#field-names-and-titles), or (b) creating a temporary copy of the schema with [additional `rollUp` properties](https://flatten-tool.readthedocs.io/en/latest/create-template/#rolling-up) and then [generating template from the schema](https://flatten-tool.readthedocs.io/en/latest/usage-360/).

**Comment by RKHayden** [comment] 2018-10-02 15:56
@Lawrence-G I think the problem is with both the schema and the framework. The framework can lead to the same funds being counted multiple times. For example, research funding is allocated to some research funders through a 'Grant in Aid'. Those funds are then allocated by research funders to researcher organisations or researchers using grants. An issue that I recall being raised during the alpha phase for GGIS was that a grant funder may aggregate funds from multiple departments and then disperse those funds, so an individual grant can include funds from multiple government departments, so eliminating that double counting could be difficult.

Although the government grants register includes research and innovation grants, many of those (for example the BEIS grants with programme titles starting 'RCUK') are actually a rolled up value of multiple grants - which I believe is done in part because of the difficulty of fitting individual RCUK grants to the schema. Many of the CLG Local Government 'grants' also looked like rolled up values of funds that would have been further distributed, possibly through grants, by local authorities.

I can see in the schema what appear to me to be some assumptions or difficulties. For example, identifying the beneficiary location - the definitions appear to me to imply a level of specificity that may not be appropriate (medical research into some diseases might benefit a large part of a continent, for example). Another example is organisation identifiers. My first attempt using the org-id.guide to find an identifier for a research organisation in a particular country (chosen almost at random) got a result of "We can't provide any suggested results for your query" My second attempt, searching for research organisations in a country I know the UK has joint research programmes with, resulted in a list of companies, which isn't the same thing. Several years ago, when looking at the RCUK data during the GGIS alpha, even within the UK there were organisations receiving funding for which it was difficult to find an identifier.

**Comment by timgdavies** [comment] 2018-10-02 16:03
@RKHayden For research organisations, you may want to check org-id.guide results for the 'Research' sector: http://org-id.guide/results?structure=all&coverage=all&sector=research

I've often found http://org-id.guide/list/XI-GRID provides reasonable results for locating research institutions.

That said, organisation identifiers and beneficiary locations are not a mandatory part of 360Giving standard: it's schema validation is very permissive, so it encourages a 'best efforts' approach to including these, and specifies how to represent them where they are available - rather than mandating that they should be published.

Double-counting is an issue of implementation, rather than the standard itself. 

There has been extensive work in the context of aid on addressing 'traceability' - and I think the simple conclusion is that without central co-ordination, you can't easily eliminate the risk that anyone aggregating a corpus of data about funding flows will not 'double count' information. I think the solutions here have to lie with helping users make sensible judgements about their analysis - and understanding that certain funders grants are likely to be onwardly reflected in one or more other funders datasets.

**Comment by RKHayden** [comment] 2018-10-02 16:51
@timgdavies The schema has "Recipient Org:Identifier" as mandatory and although that includes an option of basing an identifier on a funders own IDs, that wouldn't be useful if those IDs aren't publicly available (which in the case I was involved in, they weren't).

Although the 360Giving standard may encourage a 'best efforts' approach, I'm not convinced that translates well into its use by government. Going back to the GGIS alpha, where a best efforts approach would have resulted in data for certain fields only being included for some grants, some of the grant funders took the view that it was better to exclude that data for all grants in their portfolio, owing to the risk of the absence of data being incorrectly interpreted. That doesn't serve the user needs identified at the top of this thread, but the uses of public grants data go far wider than those.

**Comment by timgdavies** [comment] 2018-10-02 17:04
An identifier based on a publishers internal ids are still useful for some use cases (or even a hash of those identifiers when there is some reason for not disclosing the original 'internal' ids). For example, it makes it possible to at least understand the range of different organisations that funder has made grants to, and patterns of repeat granting to organisations. 

It is of course more useful when the identifier can be linked across publishers, but the fact of not being able to publish globally unique common identifiers does not seem to be to be a reason against adoption of 360 Giving.

Can you articulate some concrete user requirements needed for a standard covering government grants that are distinct of those covered by 360 Giving at present. 

Note that 360 Giving was modelled on IATI (used globally by governments for aid funding flows) and the Open Contracting Data Standard (also used for complex financial flows information).

**Comment by RKHayden** [comment] 2018-10-03 11:30
@timgdavies I don't mean to suggest the 360Giving schema not be adopted as a standard, but for any standard there needs to be an understanding of its limitations and of the impact those limitations may have on the data, particularly in how the absence of data is interpreted.

I'm not close enough to this work now to give concrete user needs. A major one that I recall from involvement in the GGIS alpha was for government to be able to see who the recipients of funding were across government, for fraud prevention. So if an organisation is receiving funding in both grants and contracts from multiple departments and agencies, there is a need to be able to aggregate that to ensure the same work is not being funded more than once. Unique common identifiers are key to doing that.

**Comment by morchickit** [comment] 2018-10-11 13:03
Hi @RKHayden - for your concern about identifiers, as Tim mentioned, this is not only 360Giving concern but other standards as well. I believe this is even a bigger issue that needs to be addressed across government. We even wrote about it a couple of time on our blog - http://www.threesixtygiving.org/2018/05/21/little-unique-codes-hold-world-together/

We are doing work to help publish consistent identifiers as we can not only for the government, but for other grantmakers. We have some preliminary work on it here: https://github.com/ThreeSixtyGiving/ID-reconcile/issues

**Comment by markbrough** [comment] 2018-10-12 18:45
I agree with @morchickit. Globally unique identifiers are preferable but we have to be realistic / pragmatic / flexible to begin with, otherwise initial implementation of the standard could imply much larger up-front costs.

* `Recipient Org:Identifier` is a required field, but it's not required for it to be a globally unique identifier. It can just be an internal identifier if a global identifier is not available.
* Internal identifiers can be somewhat useful if they are used consistently, because a) they identify the same organisation consistently for one publishing organisation and b) third parties can start to map together the sets of identifiers used by each publishing organisation.
* It would clearly be beneficial if a globally unique identifier were used instead, and organisations should be encouraged to do that.
* But of course, these identifiers may not always be available in source systems, so it is good to maintain some flexibility here.

I think the same goes for beneficiary location -- it is not a required field, and while it can (should) be provided if available, it can also be left out if not.

On @RKHayden's point around (as I understand it) aggregation of individual grants into sets of grants, I don't agree this is really a problem. In general, I think some data is better than no data, and while it would be preferable for individual grants to be published, if grants are aggregated/grouped together, this data can still be useful.

I think the 360 Giving Standard is solid and well-designed and appropriate for adoption as a data standard. Experience with IATI has shown that standards that allow for flexibility can provide low barriers to entry to initial implementation, while allowing for data to gradually be improved over time. The Publish What You Fund [Aid Transparency Index](http://www.publishwhatyoufund.org/the-index/comparison-chart/) shows how organisations' performance gradually improved over time (the Index has quality publication under the IATI open data standard as by far the highest-scoring form of transparency). The number of organisations rated as "good" or "very good" doubled in three years, from 9 to 18.

**Comment by morchickit** [comment] 2018-10-19 14:24
HI all, 

Here is our submission for to Open Standard board: 

### Introduction
This proposal is for the 360Giving standard to be used in the disclosure of government grants data. The 360Giving standard provides established specification for publishing structured data of financial transactions of grants. 

The 360Giving standard was designed to allow grantmakers to share information about their funding to support greater collaboration and transparency in the charity sector. It was designed with the UK grantmaking space in mind. It is flexible enough to allow different funders to customise it to their own processes while maintaining interoperability with other grantmakers’ data. 

The outcomes of using the standard include being able to see all government grants in a comparable, open format alongside grants made by other funding organisations including local authorities, charitable trusts and foundations and the lottery funds. This will help government and civil society to more easily identify and understand where money is being invested and support better collaboration to advance the charity sector in the UK. 

More on the challenge can be found on [GitHub](https://github.com/alphagov/open-standards/issues/63). 

### User Needs Approach 
The main users of the 360Giving standard are bodies that give grants to other organisations. This includes:
Public bodies such as government departments, local authorities and lottery funders
Charitable trusts and foundations 

In addition, people are using the disclosed information to conduct research and develop insights from it. In addition to the users listed above, this group includes:
Organisations that are seeking funding sources 
Organisations that are developing tools and platforms that include funding data and other data
Academia
Journalists
Private citizens

The different users needs are met because:
The standard includes all the mandatory fields that are helpful for analysing the flow of grants.
The ability to include extra fields in the standard allows for expanding the disclosure of data according to different grantmakers’ needs. 
The flat structure of the standard makes it straightforward to publish data in the required format and allows easy analysis between different funders. 
Files are available in CSV and JSON for easy analysis by both developers and researchers. 
Documentation is available to help onboard users who are not familiar with grantmaking. It is reviewed and updated on a regular basis. 


### Achieving the expected benefits
The 360Giving standard allows organisations to publish their grants data in an open, structured way that helps people to understand
and use the data more easily to support decision-making and learning across the charitable giving sector.

If government joins other grantmakers and shares its grants data in the 360Giving standard, this will dramatically increase the amount of open, comparable data available on grants awarded across the UK. This data can be used to support decision-making and learning among different groups and in different contexts, resulting in changed approaches throughout the sector. 

By structuring the data, the standard supports the core infrastructure of the grantmaking sector. This will help to improve the quality of the data that is shared by grantmakers. It will also support better analysis and understanding of the flow of funds being provided both across government and by independent funders. 

### Functional needs
360Giving version 1.0 is a publishing framework which covers all the required functional needs within the core specification. 
A 360Giving dataset is a relational dataset which can allow representing one to many relationships that can be represented in JSON or CSV file formats. The standard has 10 mandatory fields and more than 50 which can help provide more context on the grants.
Other steps to achieving interoperability 
As an open standard, 360Giving has an independent Stewardship Committee which is made up of representatives from 360Giving staff and board members, current and potential publishers, end users of 360 data and technical experts. The Committee is responsible for approving formal upgrades of the Standard and ensuring the agreed [governance process](http://standard.threesixtygiving.org) has been properly adhered to. When making any changes or upgrades to the standard, the Stewardship Committee discuss approaches used by other relevant standards such as the Open Contracting and IATI standards. 

For organisation identification, 360Giving builds on the [org-id.guide](http://org-id.guide/) codelist, used in both IATI and Open Contracting data, supporting joined-up data between grants, international aid and contracting. 
360Giving builds upon existing open standards, including JSON and CSV, and makes use of ISO 8601 compatible dates.

**Closed as completed** 2019-03-08 11:42 UTC
Labels: Challenge, Mandated
